python_library(
	name="global-services",
	sources=rglobs("*"),
)

python_library(
    name="grouping-services",
    sources=["group_segments/*"],
)

python_library(
    name="action_item_detector",
    sources=["action_item_detector/*"],
)

python_library(
    name="bert_ner",
    sources=["bert_ner/*"],
)
