python_library(
    name='graphrank',
    sources=['*'],
    dependencies=[
        ':version',
        '3rdparty/python:spacy',
		'3rdparty/python:pandas',
		'3rdparty/python:nltk',
		'3rdparty/python:networkx',
		'3rdparty/python:python-louvain',
    ]
)


python_library(
  name='version',
  sources=['__version__.py']
)