name: CI

on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Flake8 Code Linter
      uses: jonasrk/flake8-action@master
      with:
        args: "--max-line-length=79 --exclude .ipynb --ignore E203, E266, E501, W503, F403, F401"