name: CI

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Github Actions
      uses: actions/checkout@v1
    - name: black code formattor 
      uses: lgeiger/black-action@v1.0.1
      with:
        args: ". --exclude .pants.d --check --diff"
